version: 0.1
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  build:
    commands:
      - ./node_modules/.bin/serverless deploy --stage cicd | tee deploy.out
  post_build:
    commands:
      - ./test.sh