# serverless.yml

service: my-express-application

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-west-2

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'